"""routes and models for /admin

Revision ID: 086239b0ed72
Revises: 5a96026f2c7b
Create Date: 2024-09-23 10:12:26.027074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '086239b0ed72'
down_revision = '5a96026f2c7b'
branch_labels = None
depends_on = None


def upgrade():
    # Get the inspector to check if the column exists
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [column['name'] for column in inspector.get_columns('user')]

    if 'is_admin' not in columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('is_admin', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
