"""Add nullable revision_number to Vote

Revision ID: 2caf9d16482e
Revises: c02c78a2c859
Create Date: 2024-09-22 09:00:26.838232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2caf9d16482e'
down_revision = 'c02c78a2c859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('revision_number')

    # ### end Alembic commands ###
