"""Vote and Chart classes

Revision ID: 34d0974e32ed
Revises: 748cf955764d
Create Date: 2024-09-19 15:20:18.292785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d0974e32ed'
down_revision = '748cf955764d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_data', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_vote', sa.Integer(), nullable=False),
    sa.Column('vote_time', sa.DateTime(), nullable=False),
    sa.Column('interacting_user', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['interacting_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_chart_id'), ['chart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_interacting_user'), ['interacting_user'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_chart', sa.Integer(), nullable=True))

    with op.batch_alter_table('user__login', schema=None) as batch_op:
        batch_op.drop_index('ix_user__login_login_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__login', schema=None) as batch_op:
        batch_op.create_index('ix_user__login_login_time', ['login_time'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_chart')

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_interacting_user'))
        batch_op.drop_index(batch_op.f('ix_vote_chart_id'))

    op.drop_table('vote')
    op.drop_table('chart')
    # ### end Alembic commands ###
