"""Make revision_number non-nullable after fixing bug 

Revision ID: 5a96026f2c7b
Revises: 2caf9d16482e
Create Date: 2024-09-22 09:09:08.559934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a96026f2c7b'
down_revision = '2caf9d16482e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('revision_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('revision_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
