"""added revision_number to Vote class

Revision ID: c02c78a2c859
Revises: 34d0974e32ed
Create Date: 2024-09-21 20:00:02.408269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02c78a2c859'
down_revision = '34d0974e32ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('revision_number')

    # ### end Alembic commands ###
